version: '3.8'

services:
  movie-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - CRAWLER_API_BASE_URL=${CRAWLER_API_BASE_URL}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - crawler-api
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    networks:
      - app-network

  crawler-api:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DB_PORT=${DB_PORT}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge