version: '3.8'

services:
  crawler-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DB_PORT=${DB_PORT}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge